name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Publish
      run: dotnet publish --configuration Release
    - name: Copy dockerfile  
      uses: canastro/copy-action@0.0.2
      with:
       source: /home/runner/work/Dotnet.Url.Jumper/Dotnet.Url.Jumper/DevOps/Dockerfile
       target: /home/runner/work/Dotnet.Url.Jumper/Dotnet.Url.Jumper/Dotnet.Url.Jumper.UI/bin/Release/net5.0/publish/
    - uses: docker/setup-buildx-action@v1.1.2
    
